before_deploy:
- openssl aes-256-cbc -K $encrypted_e5e02ce89fac_key -iv $encrypted_e5e02ce89fac_iv
  -in id_rsa_macops_ca_deploy.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
cache: bundler
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
language: ruby
script:
  - bundle exec jekyll build --trace
