addons:
  ssh_known_hosts: macops.ca
before_deploy:
- openssl aes-256-cbc -K $encrypted_e5e02ce89fac_key -iv $encrypted_e5e02ce89fac_iv
  -in id_rsa_macops_ca_deploy.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  - HUGO_VERSION=0.24.1
  - PYGMENTS_VERSION=2.2.0
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
  - pip install pygments==${PYGMENTS_VERSION}
language: python
python:
  - "3.6"
script:
  - hugo -v
