name:               "Mac Operations"
url:                "https://macops.ca"
baseurl:            ""
permalink:          "/:title"
timezone:           "America/Montreal"
date_format:        "%B %-d, %Y"

# Conversion
# markdown:           kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
markdown:           redcarpet
redcarpet:
  extensions: [with_toc_data]

# Navigation
nav:
  - name:           "About"
    href:           "about"
  - name:           "Talks"
    href:           "talks"
  - name:           "Links"
    href:           "links"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Site generation
exclude:
  - bin
  - '*.sh'
  - Gemfile*
  - README*

# Rake tasks
post:
  template: _rake_templates/post.txt
  extension: md
page:
  template: _rake_templates/page.txt
  extension: md
editor: Sublime Text 3.app
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination: ~/Git/username.github.com/
